### ISSUE TITLE
missing dataset_dicom.py

### ISSUE THREAD

**Issue by omdona** [shizuo-kaji/UnpairedImageTranslation#1]

**Comment by johnrickman** [comment]
@shizuo-kaji do you have a working example of using dicom images?

**Comment by johnrickman** [comment]
I figured out my issues. For DCM images the 'SliceLocation' should be an argument as this key is different for each manufacturer - Siemens uses 'ImagePositionPatient' which is an array with the second index being the image offset. 

Please let me know if you would like me to submit a PR.

**Comment by omdona** [comment]
Hi !
It was a good idea generalizing the code for all manufacturers. 
You can send a PR if you want, although I dont think this github account is active at all. Perhaps you could add this as a comment on stack exchange 

Olga

**Comment by johnrickman** [comment]
Hi @omdona ,

Glad you like my idea :). I forked the repo and will start commiting updates as I work on my project. I hope it will help your project too!

**Comment by shizuo-kaji** [comment]
Thank you for your comment, and I am sorry for my quick and dirty handling of dicom files. I am not familiar with dicom files.

**Comment by johnrickman** [comment]
No problem! Thanks for giving me a good starting point for my project! 👍
