### ISSUE TITLE
Unknown variable 't'

### ISSUE THREAD

**Issue by johnrickman** [shizuo-kaji/UnpairedImageTranslation#2]
I am getting warnings regarding an unset variable 't' in updater.py. Can you tell me what the use of this variable is? https://github.com/shizuo-kaji/UnpairedImageTranslation/blob/8f5c977a3871c9cd9ac486f76b829d75a18f0b3f/updater.py#L209

**Comment by shizuo-kaji** [comment]
Thank you for spotting the bug. You can just remove it. 
In any case, Wasserstein GAN does not seem to work well and LSGAN performs better.
